version: '3.18'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5431:5439
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: tomide@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin_password

networks:
  local:
    name: local
    driver: bridge
