version: '3.18'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres


networks:
  local:
    name: local
    driver: bridge
