version: '3.18'

services:

  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: KleenDb
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password

networks:
  local:
    name: local
    driver: bridge
