version: '3.18'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: tomide@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin_password

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
    grafana-data:

networks:
  local:
    name: local
    driver: bridge
