
logging:
  level:
    org.springframework.security: DEBUG

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  config:
    import: optional:secret.properties


server:
  port: ${PORT:8080}
