
logging:
  level:
    org.springframework.security: DEBUG

spring:
  config:
    import: optional:secret.properties

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${PORT:8080}
