spring:
  datasource:
    url: jdbc:postgresql://${HOST}:${DB_PORT}/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:secret.properties


logging:
  level:
    org.springframework.security: DEBUG

